"""Enable custom account types

Revision ID: d08d0b37788a
Revises: 0ae4ef82b244
Create Date: 2016-05-19 18:36:18.693108

"""

# revision identifiers, used by Alembic.
revision = 'd08d0b37788a'
down_revision = '0ae4ef82b244'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('account_type_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('value', sa.String(length=256), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'account', sa.Column('account_type_id', sa.Integer(), nullable=False))
    op.add_column(u'account', sa.Column('identifier', sa.String(length=256), nullable=True))
    op.create_foreign_key(None, 'account', 'account_type', ['account_type_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'account', type_='foreignkey')
    op.drop_column(u'account', 'identifier')
    op.drop_column(u'account', 'account_type_id')
    op.drop_table('account_type_values')
    op.drop_table('account_type')
    ### end Alembic commands ###
